### ISSUE TITLE
The client doesn't refresh the refresh-token every 45 days.

### ISSUE THREAD

**Issue by MGelbana-Incorta** [onelogin/onelogin-java-sdk#19]
According to [this page](https://developers.onelogin.com/api-docs/1/oauth20-tokens/refresh-tokens), the refresh token expires after 45 days and the client dosn't seem to track this time. So it looks like if a client instance if instantiated and stays alive for more than 45 days, the resfresh token will be expired then and the client will always fail to refresh the authentication token.

**Comment by pitbulk** [comment]
You are right.

The refresh token expires in 45 days if no refresh is made in this time.

On each call we verify that the access token has not expired, otherwise we refresh the token.
(prepareToken method).

We assume that this will keep the token refreshed so the 45 days count never gonna happen, but yes you are right that if no call is made in 45 days, the token expires.

I think is ok to have another expiration time of 45 days set when the token is generated, reset its expiration when the token is refreshed and checked its value on prepareToken has we do with the expiration time of the access token.

**Comment by MGelbana-Incorta** [comment]
> if no call is made in 45 days, the token expires

Are you saying that the refresh-token doesn't expire if it's used often enough to refresh access-tokens ?
I believe that's not true because the docs doesn't seem to mention that. Please correct me if I'm wrong.

**Comment by pitbulk** [comment]
From the link  you previously shared:

A refresh token is valid for 45 days after generation, as long as you have not refreshed or revoked it. So, for example, if your access token has expired, but its refresh token has not yet expired, you can use them to generate a new set of tokens (refresh tokens).

**Comment by MGelbana-Incorta** [comment]
> you can use them to generate a new set of tokens (refresh tokens).

I thought it's referring to access-tokens, not refresh-tokens as you clarified. Thanks.

**Comment by pitbulk** [comment]
I think the API behavior changed but the code was not updated.
Current behavior is that the refresh_token is not regenerated with the "Refresh Tokens" action.

In order to get a new access_token and refresh_token, dev must 1st revoke current token and then call to generate token method.

I don't think SDK may maintain the "expiration" of the refresh token for 45 days, since the initial access_token could be made in other place or in other execution.
